const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
window.addEventListener('load',()=>setTimeout(()=>$('.loader')?.classList.add('done'),850));
const cursor=$('.cursor'),dot=$('.cursor-dot');
window.addEventListener('pointermove',e=>{if(cursor){cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px';dot.style.left=e.clientX+'px';dot.style.top=e.clientY+'px'}});
const refreshCursor=()=>$$('a,button').forEach(el=>{el.addEventListener('mouseenter',()=>cursor?.style.setProperty('transform','translate(-50%,-50%) scale(1.45)'));el.addEventListener('mouseleave',()=>cursor?.style.setProperty('transform','translate(-50%,-50%) scale(1)'))});
refreshCursor();
const words=$('.swap'); if(words){const list=words.dataset.words.split('|');let i=0;setInterval(()=>{words.classList.add('change');setTimeout(()=>{i=(i+1)%list.length;words.firstChild.nodeValue=list[i];words.classList.remove('change')},250)},2200)}
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.12}); $$('.reveal').forEach(e=>io.observe(e));
const track=$('.horizontal-track'),hsec=$('.horizontal-section'),progress=$('.h-progress span');
function horizontal(){if(!track||!hsec)return;const r=hsec.getBoundingClientRect(),max=hsec.offsetHeight-innerHeight,p=Math.min(1,Math.max(0,-r.top/max));track.style.transform=`translate3d(${-p*66.6667}%,0,0)`;if(progress)progress.style.transform=`scaleX(${Math.max(.03,p)})`}
window.addEventListener('scroll',horizontal,{passive:true});horizontal();
const nav=$$('.side nav a'); const sections=['top','about','work','services','process','contact'].map(id=>document.getElementById(id));
const activeIO=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)nav.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}),{rootMargin:'-40% 0px -45% 0px'});sections.forEach(s=>s&&activeIO.observe(s));
$$('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const t=document.querySelector(a.getAttribute('href'));if(t){e.preventDefault();t.scrollIntoView({behavior:'smooth'})}}));

const services={
 '01':{kicker:'03 / WHAT I DO — DESIGN',title:'Design',intro:'Визуальная система, которая помогает бизнесу выглядеть цельно, понятно и узнаваемо.',image:'design.jpg',label:'FIGMA / VISUAL / UI',tags:['Figma','Photoshop','VK','Visual system'],items:['Разбираю задачу и визуальное направление','Собираю айдентику и систему графики','Упаковываю соцсети и рекламные форматы','Готовлю презентации и полиграфию','Передаю понятные правила для дальнейшей работы'],note:'Фокус не на количестве макетов, а на цельной системе, которую можно развивать.'},
 '02':{kicker:'03 / WHAT I DO — WEB',title:'Web',intro:'Сайт как инструмент: от структуры и первого экрана до адаптива и запуска.',image:'web.jpg',label:'WEB / UI / UX / CODE',tags:['Figma','Tilda','HTML / CSS / JS','Responsive'],items:['Формирую структуру и UX-сценарий','Проектирую первый экран и путь пользователя','Собираю UI и визуальную систему','Адаптирую под desktop и mobile','Подготавливаю сайт к публикации'],note:'Сайт должен не просто выглядеть хорошо — он должен понятно вести человека к нужному действию.'},
 '03':{kicker:'03 / WHAT I DO — SMM',title:'SMM',intro:'Упаковка и контент-система, которая помогает бренду говорить единым голосом.',image:'smm.jpg',label:'VK / TELEGRAM / SOCIAL',tags:['VK','Telegram','Instagram','Content'],items:['Упаковываю профиль или сообщество','Разрабатываю контент-концепцию','Придумываю темы постов, Reels и Shorts','Собираю визуальные шаблоны','Формирую направление для регулярного контента'],note:'Система должна быть удобной в работе и сохранять единый характер бренда от публикации к публикации.'},
 '04':{kicker:'03 / WHAT I DO — MARKETING',title:'Marketing',intro:'Креатив и коммуникация вокруг задачи бизнеса — от идеи до визуального воплощения.',image:'marketing.jpg',label:'CREATIVE / ADS / GROWTH',tags:['Concept','Creative','Ads','Content'],items:['Нахожу идею и угол подачи','Придумываю креативные концепции','Собираю рекламные визуалы','Адаптирую идею под разные каналы','Связываю дизайн, контент и коммуникацию'],note:'Задача маркетингового визуала — быстро донести ценность и вызвать нужное действие.'}
};
const cases={
 brand:{kicker:'02 / PROJECTS — SOCIAL SYSTEM',title:'Визуальная система',intro:'Как можно собрать социальные сети в единый визуальный язык: от направления до регулярного контента.',image:'smm.jpg',label:'SOCIAL / CONTENT / SYSTEM',tags:['VK','Content','Visual'],items:['Определяем задачу, аудиторию и характер бренда','Собираем визуальное направление и правила','Проектируем шаблоны для регулярного контента','Адаптируем систему под разные форматы','Закладываем основу, которую можно масштабировать'],note:'Демонстрационный кейс. Реальные работы и фактические результаты добавим после загрузки портфолио.'},
 web:{kicker:'02 / PROJECTS — WEB',title:'Сайт, который ведет',intro:'Концепция сайта, где структура, визуал и текст работают как один маршрут пользователя.',image:'web.jpg',label:'WEB / UI / UX',tags:['Structure','UI','UX'],items:['Определяем задачу сайта и целевое действие','Собираем структуру и первый экран','Проектируем UI и визуальную иерархию','Делаем адаптивную систему','Готовим к публикации и дальнейшим правкам'],note:'Демонстрационный кейс. Это концепция процесса, а не заявление о конкретном выполненном проекте.'},
 marketing:{kicker:'02 / PROJECTS — MARKETING',title:'Идея, которую видят',intro:'Креативная концепция для коммуникации продукта через сильный визуальный образ.',image:'marketing.jpg',label:'CAMPAIGN / CREATIVE',tags:['Concept','Ads','Content'],items:['Формулируем сообщение и задачу кампании','Находим визуальную метафору','Собираем главный рекламный образ','Делаем адаптации для разных форматов','Связываем рекламу с контентом бренда'],note:'Демонстрационный кейс. Позже заменим его реальной работой из портфолио.'}
};
const routePage=$('#routePage'), routeKicker=$('#routeKicker'),routeTitle=$('#routeTitle'),routeIntro=$('#routeIntro'),routeTags=$('#routeTags'),routeImage=$('#routeImage'),routeArtLabel=$('#routeArtLabel'),routeItems=$('#routeItems'),routeNote=$('#routeNote'),routeCount=$('#routeCount');
function renderRoute(type,id,push=true){const d=(type==='service'?services:cases)[id];if(!d)return;routeKicker.textContent=d.kicker;routeTitle.textContent=d.title;routeIntro.textContent=d.intro;routeTags.innerHTML=d.tags.map(x=>`<span>${x}</span>`).join('');routeImage.src=d.image;routeImage.alt=d.title;routeArtLabel.textContent=d.label;routeItems.innerHTML=d.items.map((x,i)=>`<div class="route-item"><b>${String(i+1).padStart(2,'0')}</b><p>${x}</p><span>+</span></div>`).join('');routeNote.textContent=d.note;routeCount.textContent=type==='service'?'SERVICE / '+id:'CASE / '+id.toUpperCase();routePage.classList.add('is-open');routePage.setAttribute('aria-hidden','false');document.body.classList.add('route-open');window.scrollTo({top:0,behavior:'instant'});if(push)history.pushState({route:type,id},'',`#${type}-${id}`)}
function closeRoute(push=true){routePage.classList.remove('is-open');routePage.setAttribute('aria-hidden','true');document.body.classList.remove('route-open');if(push)history.pushState({},'',location.pathname+location.search);}
$$('.service-trigger').forEach(b=>b.addEventListener('click',()=>renderRoute('service',b.dataset.service)));
$$('.case-trigger').forEach(b=>b.addEventListener('click',()=>renderRoute('case',b.dataset.case)));
$('#routeBack').addEventListener('click',()=>history.back());
$$('.contact-trigger').forEach(b=>b.addEventListener('click',()=>{closeRoute(false);document.querySelector('#contact')?.scrollIntoView({behavior:'smooth'});}));
window.addEventListener('popstate',()=>{const m=location.hash.match(/^#(service|case)-(.+)$/);if(m)renderRoute(m[1],m[2],false);else closeRoute(false)});
window.addEventListener('load',()=>{const m=location.hash.match(/^#(service|case)-(.+)$/);if(m)renderRoute(m[1],m[2],false)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&routePage.classList.contains('is-open'))history.back()});
